---
- hosts: localhost
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
    - name: Copy file to windows server
      win_copy:
        src: /home/ubuntu/
        dest: skadaverugu@192.168.100.11:C:\Users\skadaverugu\Desktop

